# Generated by Django 5.1.4 on 2025-01-05 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('food_demand_predictions', models.JSONField()),
                ('delivery_routes', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='CommunityFridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('manager_name', models.CharField(max_length=255)),
                ('manager_contact', models.CharField(max_length=15)),
                ('capacity_kg', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='FoodSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=15)),
                ('source_type', models.CharField(choices=[('GROCERY', 'Grocery Store'), ('RESTAURANT', 'Restaurant'), ('FARM', 'Farm')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionWorkshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('instructor_name', models.CharField(max_length=255)),
                ('max_participants', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='medication',
        ),
        migrations.AddField(
            model_name='customuser',
            name='family_members',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.IntegerField(default=354133, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='SurplusFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(max_length=100)),
                ('quantity_kg', models.FloatField()),
                ('expiry_date', models.DateField()),
                ('donated_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surplus_foods', to='app.foodsource')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('delivery_date', models.DateField()),
                ('delivery_status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered')], max_length=50)),
                ('surplus_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='app.surplusfood')),
            ],
        ),
    ]
