# Generated by Django 5.1.4 on 2025-01-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_aimodeldata_communityfridge_foodbank_foodsource_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunityFridge',
        ),
        migrations.DeleteModel(
            name='NutritionWorkshop',
        ),
        migrations.RemoveField(
            model_name='foodbank',
            name='address',
        ),
        migrations.RemoveField(
            model_name='foodbank',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='foodbank',
            name='contact_phone',
        ),
        migrations.AddField(
            model_name='foodbank',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='foodbank',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='foodbank',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodbank',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodbank',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodbank',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='foodbank',
            name='resource_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='foodbank',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='foodbank',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='foodbank',
            name='web_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodbank',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.IntegerField(default=743202, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='foodbank',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
